apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ecodigital
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: 'true'
    spec:
      containers:
        - image: REPLACE_WITH_IMAGE
          ports:
            - containerPort: 3010
          env:
            - name: NODE_ENV
              value: 'production'
            - name: DEPLOYMENT_TYPE
              value: 'selfhosted'
            - name: DEPLOYMENT_PLATFORM
              value: 'gcp'
            - name: AFFINE_SERVER_EXTERNAL_URL
              value: 'https://REPLACE_WITH_DOMAIN'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ecodigital-database-url
                  key: latest
            - name: REDIS_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: ecodigital-redis-host
                  key: latest
